/**
 * Export pack. One zip per job (or per day) containing everything you need to
 * publish by hand: mp4, srt, thumbnail, title, description, tags, the scheduled
 * time, and a publish checklist.
 *
 * YouTube OAuth upload is deliberately out of the MVP — this is the handoff.
 */

import archiver from "archiver";
import { Readable } from "node:stream";
import fs from "node:fs/promises";
import type { CalendarJob, Scene } from "@prisma/client";
import { readJson, readList } from "./db";
import { localPathFromUrl, isLocalMediaUrl } from "./storage";
import { MODE_META } from "./ui";
import type { Mode } from "@/pipelines/types";

export type ExportableJob = CalendarJob & { scenes?: Scene[] };

export function slugify(s: string): string {
  return (
    s
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "")
      .slice(0, 60) || "untitled"
  );
}

function fmtSchedule(d: Date | null): string {
  if (!d) return "not scheduled";
  return d.toLocaleString([], {
    weekday: "short",
    month: "short",
    day: "numeric",
    hour: "numeric",
    minute: "2-digit",
  });
}

export function buildChecklist(job: ExportableJob): string {
  const mode = MODE_META[job.mode as Mode];
  const tags = readList(job.tags);
  const inputs = readJson<{ captionVariants?: string[] }>(job.inputs, {});

  const destination =
    job.mode === "faceless_yt"
      ? "YouTube (long-form)"
      : job.mode === "zach_short"
        ? "YouTube Shorts + TikTok + Reels"
        : "TikTok + Reels + paid social";

  return `# ${job.title || job.topic}

${mode?.label ?? job.mode} · ${destination}
Scheduled: ${fmtSchedule(job.scheduledAt)}

## Publish checklist

- [ ] Watch the whole cut once with sound on
- [ ] Hook lands in the first 2 seconds
- [ ] Captions readable on a phone, nothing clipped at the edges
- [ ] Title under 60 characters
- [ ] Thumbnail reads at small size
- [ ] Description pasted, first line is the hook
- [ ] Tags pasted
- [ ] Upload captions.srt as the subtitle track
- [ ] Set publish time to ${fmtSchedule(job.scheduledAt)}
- [ ] Mark the job scheduled in Cadence

## Title

${job.title || job.topic}

## Hook

${job.hook || "—"}

## Description

${job.description || "—"}

## Caption

${job.caption || "—"}
${
  inputs.captionVariants?.length
    ? `\n### Caption variants\n\n${inputs.captionVariants.map((c, i) => `${i + 1}. ${c}`).join("\n")}\n`
    : ""
}
## Tags

${tags.length ? tags.join(", ") : "—"}

---
Generated by Cadence. Video and stills generated with the Higgsfield API.
`;
}

export function buildMetadata(job: ExportableJob) {
  return {
    id: job.id,
    mode: job.mode,
    status: job.status,
    title: job.title,
    hook: job.hook,
    caption: job.caption,
    description: job.description,
    tags: readList(job.tags),
    topic: job.topic,
    scheduledAt: job.scheduledAt?.toISOString() ?? null,
    date: job.date.toISOString(),
    provider: "higgsfield",
    scenes: job.scenes?.map((s) => ({
      order: s.order,
      seconds: s.seconds,
      narration: s.narration,
      visualPrompt: s.visualPrompt,
      camera: s.camera,
      onScreenText: s.onScreenText,
    })),
  };
}

async function addFile(
  archive: archiver.Archiver,
  url: string | null,
  name: string,
): Promise<boolean> {
  if (!url || !isLocalMediaUrl(url)) return false;
  const abs = localPathFromUrl(url);
  try {
    await fs.access(abs);
  } catch {
    return false;
  }
  archive.file(abs, { name });
  return true;
}

/** Add one job's files under `prefix` (empty string = zip root). */
export async function addJobToArchive(
  archive: archiver.Archiver,
  job: ExportableJob,
  prefix = "",
): Promise<void> {
  const p = prefix ? `${prefix}/` : "";
  const base = slugify(job.title || job.topic);

  await addFile(archive, job.videoUrl, `${p}${base}.mp4`);
  await addFile(archive, job.srtUrl, `${p}captions.srt`);
  await addFile(archive, job.thumbnailUrl, `${p}thumbnail.jpg`);
  await addFile(archive, job.voiceUrl, `${p}voiceover.wav`);

  archive.append(buildChecklist(job), { name: `${p}publish-checklist.md` });
  archive.append(JSON.stringify(buildMetadata(job), null, 2), {
    name: `${p}metadata.json`,
  });
  archive.append(job.title || job.topic, { name: `${p}title.txt` });
  archive.append(job.description || "", { name: `${p}description.txt` });
  archive.append(readList(job.tags).join(", "), { name: `${p}tags.txt` });
  if (job.script) archive.append(job.script, { name: `${p}script.txt` });
}

/** Zip one or more jobs and hand back a web stream for the route to return. */
export function streamZip(
  build: (archive: archiver.Archiver) => Promise<void>,
): ReadableStream {
  const archive = archiver("zip", { zlib: { level: 6 } });
  archive.on("warning", (e) => console.warn("[zip]", e.message));
  archive.on("error", (e) => console.error("[zip]", e.message));

  void build(archive)
    .then(() => archive.finalize())
    .catch((err) => {
      console.error("[zip] build failed:", (err as Error).message);
      archive.abort();
    });

  return Readable.toWeb(archive) as ReadableStream;
}
